apiVersion: v1
kind: Service
metadata:
  name: bookmyshow-service
  labels:
    app: bookmyshow
spec:
  type: LoadBalancer
  selector:
    app: bookmyshow
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
      name: http
